### ISSUE TITLE
Sample solutions needed for all languages.

### ISSUE THREAD

**Issue by alectunbridge** [MCR-Digital/apprentice-boot-camp-fundamentals-1#22] opened 2019-11-20 14:07 UTC
Sample solutions are only available for Java - should include other languages as well.
Since the exercises build on one another the sample solutions are important, lest those who are struggling get stuck.

**Comment by mrmanc** [comment] 2021-03-08 16:13
To do:
- [ ] Find someone to help with C#
- [ ] Create JS solutions

**Comment by mrmanc** [comment] 2021-11-02 16:26
This is a duplicate of #83

**Closed by mrmanc** 2021-11-02 16:26 UTC
Labels: duplicate, priority, please-help
